### PR TITLE
fix find-command bug by allowing more than 2 field

### LINKED ISSUE #170: Find commands should be able to search by multiple parameters
find-d and find-i should be able to search with multiple parameters. The search should be an "or" search, meaning as long as one of the parameters has a match, that item/delivery is shown

### PR DESCRIPTION
**Pull request by bobbylaw**
- [x] refactored each field to have its own predicate so that it is more OOP
- [x] Add more test case to find 
- [x] Update UG/DG
- [x] ResultsDisplay in multiple lines

Fix [#174] and [#170]
To make it more OOP, I have refactored the main predicate into different predicates hence more field can be specified and created. It will then be combined with Predicate#add to create a final predicate to be passed into FindItemCommand or FindDeliveryCommand.

Issue faced for testcases, I was unable to compare predicate to ensure that the parser is creating the correct predicate hence  shifted the tests to ItemFindCommandTest and DeliveryFindCommandTest to ensure that it manages to search with two fields and above.
 
When this is done, find command is able to search with more fields (eg. find-i n/chicken s/NTUC) will return item matching name -> chicken AND supplier -> NTUC

### CODE REVIEW

**Comment by Wincenttjoi** [comment]
@zeranium97 think you forgot to checkstyle first

**Comment by saad-haider-pp** [comment]
also, locally, pull this remote master branch to your local master, then merge it to `allow-find-command-to-take-more-field` branch and resolve conflicts

**Comment by Wincenttjoi** [comment]
Feels like its much more restrictive if find command is not universal but needs the n/ p/ s/ parser infront. @AY2021S1-CS2103T-T12-1/developers thoughts on this? But since its implemented im fine with this too.

**Comment by saad-haider-pp** [comment]
I agree. I don't think it's too hard to just check whether a word in the query is contained within any of the fields either

edit: at the same time, I think this approach may be too unrestrictive.

**Review by Choo-Xing-Yu — APPROVED** [review]
LGTM! Nice work on the test cases as well!

**Pull request merged**
