### PR TITLE
Fix remove command bug

### LINKED ISSUE #105: Exception caused by remove
When using remove without prefix, eg. remove 3, exception is thrown and not handled

Suggest to fix this on master branch first instead

Capture
Capture

### PR DESCRIPTION
**Pull request by bobbylaw**
Resolves #105

"Quantity field must be provided." will be shown if field is missing
eg. remove 3

Negative quantity value has also been handled by ParserUtil#parseQuantity

### CODE REVIEW

**Comment by Wincenttjoi** [comment]
@zeranium97 Are you also catching other exceptions as the scenarios mentioned in #105 comments?

**Comment by bobbylaw** [comment]
@Wincenttjoi Nope, those command stated in #105 

1. no prefix in command
2. values other than numbers inside quantity field

**Comment by Wincenttjoi** [comment]
Do you plan to do the other exceptions? If not then I can merge this PR first for now. Thanks @zeranium97 !

**Comment by bobbylaw** [comment]
Is there any other exceptions I might have missed out for this command?

**Comment by Wincenttjoi** [comment]
> Is there any other exceptions I might have missed out for this command?

Only those 4 checkboxes i've put in #105. Can't really check if it works for all 4 in my internal application since we're still forced to do in forking workflow. If all's good then can merge 👍 Help me check on your side please

**Comment by bobbylaw** [comment]
Yup I have checked, all good

**Comment by Wincenttjoi** [comment]
LGTM thanks!

**Pull request merged**
