### PR TITLE
Branch xingyu dg contribution

### PR DESCRIPTION
**Pull request by Choo-Xing-Yu**
Update DG
- Logic API
- Use cases

Refactor CommandHistory to HistoryManager

Updated Logic UML class diagram, Logic Sequence diagram and deleteSequneceDiagram

### CODE REVIEW

**Comment by Wincenttjoi** [comment]
@xnoobftw 
- [x] do you want to add small note on ur diagram to briefly describe what XYZ is? 
- [ ] Arrow for <<Interface>> Parser on the Parser section is abit misleading, mind to remedy that to make it more coherent?
- [ ] Perhaps you can also bring the Command and Parser box bigger (filling up >80% of the space) bcs there's too much white space and its too small for people to see. Size of individual blue boxes can also increase in size if you dm 👍 
- [x] Executes labelling on command part not clear on which line it should belong to
- [x] HelpCommandResult extends from CommandResult missing
- [x] I think there's no more concrete XYZCommand since they are all extracted to the smaller commands (items, delivery, help)
image


+ Sequence diagram for logic seems ok


@AY2021S1-CS2103T-T12-1/developers feel free to discuss bcs i'm not 100% sure either

**Comment by Choo-Xing-Yu** [comment]
> @xnoobftw
> 
> * [ ]  do you want to add small note on ur diagram to briefly describe what XYZ is?
> * [ ]  Arrow for <> Parser on the Parser section is abit misleading, mind to remedy that to make it more coherent?
> * [ ]  Perhaps you can also bring the Command and Parser box bigger (filling up >80% of the space) bcs there's too much white space and its too small for people to see. Size of individual blue boxes can also increase in size if you dm 👍
> * [ ]  Executes labelling on command part not clear on which line it should belong to
> * [ ]  HelpCommandResult extends from CommandResult missing
> * [ ]  I think there's no more concrete XYZCommand since they are all extracted to the smaller commands (items, delivery, help)
>   image
> 
> * Sequence diagram for logic seems ok

1) Will do!
2) Do you mean having a solid line? Because it's how its represented in AB3
3) Do you mean increasing the font size?
4) The PUML auto generates this D:
5) Added! Thanks
6) Redo, Undo command still does! exit too

**Comment by Wincenttjoi** [comment]
> 1. Will do!
> 2. Do you mean having a solid line? Because it's how its represented in AB3
> 3. Do you mean increasing the font size?
> 4. The PUML auto generates this D:
> 5. Added! Thanks
> 6. Redo, Undo command still does! exit too

@xnoobftw 
2. Nope, I only meant the starting point of the line bcs its overlapping with the line on the left
3.  The overall box size as well as individual boxes (inside) size, and font size
image
4. Oops its fine then!
6. Yes just realized that too, my mistake!

**Comment by Wincenttjoi** [comment]
@xnoobftw try to occupy the diagram >80% of the picture! If not too small hahha.

Edit: I realized that we can't reposition the arrows, just saw the documentation hahah. Not sure if 2 is doable

**Comment by Choo-Xing-Yu** [comment]
> @xnoobftw try to occupy the diagram >80% of the picture! If not too small hahha.
> 
> Edit: I realized that we can't reposition the arrows, just saw the documentation hahah. Not sure if 2 is doable

Idt 2 and 3 is doable due to puml automating it
But does this fulfil ur requirement!

image

**Comment by Wincenttjoi** [comment]
> Idt 2 and 3 is doable due to puml automating it
> But does this fulfil ur requirement!
> 
> image

@xnoobftw 
Can check this out for 3 https://plantuml.com/skinparam
Reason being is because we need to make our dg comprehensible thats why we shdn't just leave this out even though it seems trivial

Yup looks good! (Apart from box sizing)

**Comment by Choo-Xing-Yu** [comment]
> > Idt 2 and 3 is doable due to puml automating it
> > But does this fulfil ur requirement!
> > image
> 
> @xnoobftw
> Can check this out for 3 https://plantuml.com/skinparam
> Reason being is because we need to make our dg comprehensible thats why we shdn't just leave this out even though it seems trivial
> 
> Yup looks good! (Apart from box sizing)

image
Increased fontsizes to 30!

**Comment by Wincenttjoi** [comment]
> Increased fontsizes to 30!

Thanks! Sorry one last thing, you forgot to change the link in your Logic component description, its still referring to addressbook link

**Comment by Wincenttjoi** [comment]
LGTM thanks!

**Pull request merged**
