### PR TITLE
Ui original window size [Delete your local preferences.json]

### PR DESCRIPTION
**Pull request by Wincenttjoi**
Ensure that you delete your local preferences.json before rerunning Main to reset the default value of window size.

### CODE REVIEW

**Comment by Choo-Xing-Yu** [comment]
Would it be possible for it to bypass preferences.json by ignoring the presence of it instead of manually deleting the file?

**Comment by Wincenttjoi** [comment]
@xnoobftw one way is to not put preferences.json inside gitignore, but this default value is meant for first time users. Since all of us are developers, its okay to delete it (because users perspective as first time users they will not have the preferences.json)

**Comment by Choo-Xing-Yu** [comment]
> @xnoobftw one way is to not put preferences.json inside gitignore, but this default value is meant for first time users. Since all of us are developers, its okay to delete it (because users perspective as first time users they will not have the preferences.json)

sounds good! LGTM

**Review by Choo-Xing-Yu — APPROVED** [review]
LGTM

**Pull request merged**
