### PR TITLE
Tutorial removing field

### PR DESCRIPTION
**Pull request by saad-haider-pp**
Remove the Address class and do the necessary refactoring

### CODE REVIEW

**Comment by Wincenttjoi** [comment]
You have to rebase/ merge with master first and deconflict before PR or it will get rejected

**Comment by saad-haider-pp** [comment]
@Wincenttjoi I thought just need make pull request only for the tutorial. Everyone else's pull requests I see also have conflicts

**Comment by Wincenttjoi** [comment]
@halcon-blanco I think you're doing double work as the refactoring was already done by Bobby.. Maybe its because you never pull the latest commit from master? We can discuss this tmr during our meeting

**Comment by Wincenttjoi** [comment]
Oops sorry I just realized this is for tutorial.. I thought its meant for actual PR to be merged hahah

**Comment by saad-haider-pp** [comment]
Haha no worries

**Pull request closed without merging**
