### PR TITLE
new FindCommand

### PR DESCRIPTION
**Pull request by bobbylaw**
allows find command to be able to search by name, supplier and tags

### CODE REVIEW

**Review by saad-haider-pp — COMMENTED** [review]
Pretty much LGTM! Tests are all passing and code quality looks good.

I think you should pull request from a separate branch than the master branch since we are using a forking workflow.

**Review by saad-haider-pp — DISMISSED** [review]

**Comment by bobbylaw** [comment]
@halcon-blanco my bad, I was doing it on a branch initially but accidentally merge to master when I wanted to transfer my work to be done on another computer. Will be more careful next time

**Comment by Wincenttjoi** [comment]
@zeranium97 there's conflicting files, just rebase your commits and we'll review again 👍

**Comment by saad-haider-pp** [comment]
By the way, the conflicts came because of my PR which just got merged, so just keep that in mind haha don't throw everything out

**Comment by bobbylaw** [comment]
@Wincenttjoi @halcon-blanco I have resolved the conflict, please check, not sure if I did it the right way

**Review by saad-haider-pp — APPROVED** [review]
LGTM

**Pull request merged**
